---
# custom config
k0s_use_custom_config: true
init_extra_args: "--disable-components kube-proxy"

# HA config
loadbalancer_host: 10.140.40.119

# provision, reset
context_name: staging
k0s_version: v1.23.6+k0s.0
token_expiry: "10m"
k0s_config_dir: /etc/k0s
k0s_data_dir: /var/lib/k0s
k0s_libexec_dir: /usr/libexec/k0s/
systemd_dest: /etc/systemd/system
cni_plugins_dir: /opt/cni/bin
cni_config_dir: /etc/cni/net.d
artifacts_dir: "{{ playbook_dir }}/artifacts"
token_expiry: "10m"
