---
# custom config
k0s_use_custom_config: true
# single_node
single_node: true
init_extra_args: "--single"

# cni solution of choice
cni: "cilium"
# reference: https://docs.cilium.io/en/stable/cmdref/cilium_config/
cilium_extra_args: "--set cluster-pool-ipv4-cidr=10.96.0.0/12"

# provision, reset
context_name: prod
k0s_version: v1.34.2+k0s.0
k0s_binary_path: /usr/local/bin/k0s
k0s_config_dir: /etc/k0s
kube_dir: "/home/{{ ansible_user }}/.kube"
k0s_data_dir: /var/lib/k0s
k0s_libexec_dir: /usr/libexec/k0s/
systemd_dest: /etc/systemd/system
cni_plugins_dir: /opt/cni/bin
cni_config_dir: /etc/cni/net.d
artifacts_dir: "{{ playbook_dir }}/artifacts"
token_expiry: "10m"
